# Generated by Django 4.2.7 on 2023-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nike',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
