# Generated by Django 4.2.7 on 2023-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='company')),
                ('subtitle', models.TextField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=15, null=True)),
                ('phones', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=15, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('android_link', models.URLField(blank=True, null=True)),
                ('appstore_link', models.URLField(blank=True, null=True)),
                ('about_us', models.TextField(max_length=50)),
            ],
        ),
    ]
