# Generated by Django 4.2.7 on 2023-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_us',
            field=models.TextField(max_length=500),
        ),
    ]
