# Generated by Django 4.2.7 on 2023-11-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_company_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='post_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
